version: '2'

services:
  haproxy-configtest:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./geoip.lst:/usr/local/etc/haproxy/geoip.lst:ro
    network_mode: "none"
    entrypoint: haproxy
    command: -f /usr/local/etc/haproxy/haproxy.cfg -c
