version: '2'

services:
  haproxy-configtest:
    extends:
      file: docker-compose.yml
      service: haproxy
    network_mode: "none"
    entrypoint: haproxy
    command: -f /usr/local/etc/haproxy/haproxy.cfg -c
